### ISSUE TITLE
Avg Gas per Transaction(每笔交易平均GAS费) -> Avg Cost per Transaction(每笔交易平均花费)

### ISSUE THREAD

**Issue by wk3368** [starcoinorg/starcoin-org-v3#1]
1.  stcscan.io 首页右侧的 transactionlist，计算交易的gas平均值
<img width="1952" alt="image" src="https://user-images.githubusercontent.com/171268/168977617-5bf71b37-51ab-4e63-9dc3-9a1f2af81c1e.png">

2. https://price-api.starcoin.org/main/v1/toUsdPriceFeeds?t=STC
查询 STC/USD 的价格

3. 生成 新首页的 每笔交易平均花费 
$xxx.xx

**Comment by kkkycocho** [comment]
fix: https://github.com/starcoinorg/starcoin-org-v3/commit/b498c9bf4a1f8d01cb35317593a419a0dac65a78
